### ISSUE TITLE
Gist create 405 error with some files

### ISSUE THREAD

**Issue by sckott** [ropensci/gistr#27]
On `gist_create()` with large files, at least 1.9 MB or larger (the one I found this on), github api returns a `405 - Method not allowed` and html error body

But the same file I can paste into browser to create a gist.

And same file uploaded to make a gist using an npm cli tool works fine too - but they use git, not the http api, so not a fair comparison

Weird, maybe it's something going on with `httr`

**Comment by sckott** [comment]
testing larger files, up to 6 MB or so, and they are fine

Think this has to do with escaping characters in the object. Still working out how to get around this

**Comment by sckott** [comment]
blarg!!! I can't figure this out. There's some files that don't get posted correctly and has something to do with them not being escaped correctly, but haven't quite nailed the reason. I think most files will work though...leaving for now

**Comment by sckott** [comment]
@cpsievert did you have any example files i could try for this problem. it seems like some files are fine, and others aren't, so looking for commonalities for those that don't work

**Comment by cpsievert** [comment]
Huh, `gist_create()` seems to work even for a single text file over 100MB, which is great!

```r
> cat(runif(1e7), file = "gist_test.txt")
> cat(runif(1e5), file = "gist_test.txt", append = TRUE)
> file.info("gist_test.txt")$size/1e6
[1] 100.9996
> gist_create("gist_test.txt")
<gist>5b0648bd6ebb3632b9c2
  URL: https://gist.github.com/5b0648bd6ebb3632b9c2
  Description: 
  Public: TRUE
  Created/Edited: 2015-04-09T18:58:20Z / 2015-04-09T18:58:20Z
  Files: gist_test.txt
```

And to verify it wasn't truncated:

```bash
$ git clone git@github.com:5b0648bd6ebb3632b9c2.git
Cloning into '5b0648bd6ebb3632b9c2'...
remote: Counting objects: 3, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (3/3), 40.19 MiB | 2.45 MiB/s, done.
Checking connectivity... done.
$ cd 5b0648bd6ebb3632b9c2/
/5b0648bd6ebb3632b9c2$ wc -c gist_test.txt 
100999640 gist_test.txt
```

After taking a closer look, it seems the animint example that caused me to send that PR fails due to a 422 status code -- I'll start another issue ;)

**Comment by cpsievert** [comment]
Note this is surprising since the usual restriction is 100MB -- https://help.github.com/articles/what-is-my-disk-quota/

**Comment by cpsievert** [comment]
So, if it isn't clear, I don't think I have any examples of 405 status codes, but will report if I do.

**Comment by sckott** [comment]
Yeah, that is surprising.  

> I don't think I have any examples of 405 status codes, but will report if I do.

thanks

**Comment by sckott** [comment]
moving to next milestone, need to push fixes to cran

**Comment by elerch** [comment]
I tried to copy/paste the text from the KML attached and got a 405. I then removed all but the section relevant to my use case (Pack 769 placemark), which left me with a 689 line file. It still gave me a 405. Attached is the kml. 

Interestingly, I had to compress this as zip because the file type was not supported when adding to this comment. On a hunch I went back to my gist and renamed the file from a KML extension to an XML extension, and was then able to create the gist - no 405. My guess is the API is filtering to certain "valid" extensions and returning a 405 with no explanation if the extension is unrecognized.

[SST SFF 2016.kml.zip](https://github.com/ropensci/gistr/files/607832/SST.SFF.2016.kml.zip)

**Comment by sckott** [comment]
thanks @elerch 

I just downloaded your kml file, unzipped it, and `gist_create("SST SFF 2016.kml")` worked, see gist https://gist.github.com/sckott/69bb19163574a42ab55a7ab5d3b562ea 

Not sure why it worked for me. Can you share the larger file and I'll see if that works.

**Comment by elerch** [comment]
Here you go @sckott. I just went through the same steps as yesterday and, today it works fine in a gist, so maybe my error was transient on the server end. I did notice when I pulled it into the gist yesterday there was no syntax highlighting. Today I got syntax highlighting immediately.

[SST SFF 2016 - Full.kml.zip](https://github.com/ropensci/gistr/files/609239/SST.SFF.2016.-.Full.kml.zip)

**Comment by sckott** [comment]
thanks, Yep, that full fille works for me, with syntax highlighting. I guess it was just a temporary problem on their side.
