### ISSUE TITLE
gist_create(file, knit = TRUE, source = TRUE) should work for an R script

### ISSUE THREAD

**Issue by jennybc** [ropensci/gistr#29]
Riffing on this example from `gist_create()`:

```r
file <- system.file("examples", "stuff.Rmd", package = "gistr")
gist_create(file, knit=TRUE, include_source=TRUE)
```

I define an R script like so:

```r
my_code <-"
#' ---
#' output: md_document
#' ---

#' I shall generate random numbers.
x <- rnorm(1000)

#' And I shall summarize them.
summary(x)"
my_code_file <- writeLines(my_code, file.path("~", "tmp", "foo.R"))
```

and I would expect something like this to work:

```r
gist_create(my_code_file, description = "My first R code gist via gistr",
            knit = TRUE, include_source = TRUE)
```

But instead I get this:

```r
> gist_create(my_code_file, description = "My first R code gist via gistr",
+             knit = TRUE, include_source = TRUE)
Error in readLines(if (is.character(input2)) { : 
  object 'input2' not found
```

Same result if I remove the YAML front matter, so that's not the problem.

**Comment by sckott** [comment]
@jennybc Thanks for this.  I'll take a look...

**Comment by sckott** [comment]
working on this, but also noticed issues with binary files (images) created during knit process - trying to get that solved too

**Comment by sckott** [comment]
@jennybc would you normally generate the md from that file with `rmarkdown` package (using `render()`)? or `knitr`

**Comment by jennybc** [comment]
Honestly I would click the button in RStudio, in this context. So I think that means `render()`.

**Comment by sckott** [comment]
@jennybc okay, reinstall from master, then try it again, e.g., 

```r
file <- system.file("examples", "example1.R", package = "gistr")
cat(readLines(file), sep = "\n") # peek at file
gist_create(file, knit = TRUE)
```

**Comment by jennybc** [comment]
Yes it works! But … I like this example even more because I always want the gist to have source and pretty thing.

```r
gist_create(file, description = "my description", knit = TRUE, include_source = TRUE)
```

Thanks.

**Comment by jennybc** [comment]
I just realized how garbled up my original example was. Good work figuring out what I meant to post.

So it seems the YAML front matter is quite important. Omit it and the knitted output you get in the gist is the html. How often would anyone want that? IDK but food for thought ….. Control via an argument like `output_format` of `render()` and default to markdown? I don't need a reply.

**Comment by sckott** [comment]
@jennybc just to clarify, are you saying that sometimes users may not have the front matter, so we should default to markdown output, but allow user to control via a parameter?

**Comment by jennybc** [comment]
Yes exactly. But maybe I am atypical? I basically always want markdown. In addition to or instead of HTML. Even more so for a gist than in other contexts.

**Comment by sckott** [comment]
Right, okay. I'll play around with that, #34
