### ISSUE TITLE
Does this work okay?

### ISSUE THREAD

**Issue by sckott** [ropensci/gistr#39]
@cpsievert @jennybc @karthik @cboettig if you get a second, could you test out the git functionality (vs. using the github http api)?

```r
devtools::install_github("ropensci/gistr@git2r")
library("gistr")
... # do stuff
```

see examples https://github.com/ropensci/gistr/blob/git2r/R/gist_create_git.R#L7-L29

in the `git2r` branch we're using `git2r` to push to a gist (not a github repo), since gists are git repos just as github repos are. This what mbostocks `gistup` node.js CLI tool does, using git instead of the http api. 

p.s. maybe I should add `git` functionality to `gist_create()`

**Comment by cpsievert** [comment]
I see:

```r
> stuff <- system.file("examples/stuff.md", package = "gistr")
> gist_create_git(files = stuff)
 Error in .local(object, ...) : 
  Error in 'git2r_push': Unsupported URL protocol 
```

Have people had problems installing **git2r**? If so, maybe you could suggest instead of import (and add a `requireNamespace('git2r')` in `gist_create_git()`)? The primary purpose of adding **git2r** is to request large files, right?

**Comment by sckott** [comment]
Thanks @cpsievert !  I don't know much about installation problems with `git2r` - I'll look around. I was thinking we may want to do that, not have as Import, but instead as a Suggest, 

Have you used `git2r` without problem outside of this example?

**Comment by cpsievert** [comment]
I actually had to install **git2r** to run this, and it went smoothly. Here is some more info that might help:

```r
> Sys.which("openssl")
           openssl 
"/usr/bin/openssl" 

> sessionInfo()
R version 3.1.3 (2015-03-09)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.2 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] gistr_0.1.6.9999 devtools_1.7.0  

loaded via a namespace (and not attached):
 [1] assertthat_0.1    bitops_1.0-6      DBI_0.3.1         digest_0.6.8     
 [5] dplyr_0.4.1       evaluate_0.5.5    formatR_1.0       git2r_0.7.99     
 [9] htmltools_0.2.6   httr_0.6.1.9000   jsonlite_0.9.14   knitr_1.9.3      
[13] magrittr_1.5      parallel_3.1.3    Rcpp_0.11.5       RCurl_1.95-4.5   
[17] rmarkdown_0.5.3.1 roxygen2_4.1.0    stringr_0.6.2     tools_3.1.3  
```

Also, we have [a big hack in animint to upload a screenshots via git](https://github.com/tdhock/animint/blob/master/R/gist.R#L64-L99), so this would be a big improvement :+1:

**Comment by cpsievert** [comment]
Give me a second to try out a minimal example with __git2r__

**Comment by sckott** [comment]
@cpsievert thanks for the addtn' info

**Comment by cpsievert** [comment]
I'm having trouble using `git2r::push()` to push to github. Should I open an issue over at git2r?

**Comment by sckott** [comment]
@cpsievert hmmm, let me play around real quick

**Comment by cpsievert** [comment]
Here's what I'm seeing:

```r
> path_bare <- tempfile(pattern="git2r-")
> path_repo <- tempfile(pattern="git2r-")
> dir.create(path_bare)
> dir.create(path_repo)
> repo_bare <- init(path_bare, bare = TRUE)
> repo <- clone(path_bare, path_repo)
cloning into '/var/folders/wc/zv89d1fx5nxdljsysq40m6vr0000gn/T//RtmpIGgRdb/git2r-c938743ccb1e'...
> 
> writeLines("Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do",
+            file.path(path_repo, "example.txt"))
> add(repo, "example.txt")
> commit(repo, "First commit message")
[5b895de] 2015-04-08: First commit message
> push(repo, "origin", "refs/heads/master")
> repo
Remote:   @ origin (/var/folders/wc/zv89d1fx5nxdljsysq40m6vr0000gn/T//RtmpIGgRdb/git2r-c93811d015a4)
Local:    master /private/var/folders/wc/zv89d1fx5nxdljsysq40m6vr0000gn/T/RtmpIGgRdb/git2r-c938743ccb1e/
Head:     [5b895de] 2015-04-08: First commit message
> git2r::remote_add(repo, "upstream", "https://github.com/cpsievert/git2rtest.git")
> git2r::remotes(repo)
[1] "origin"   "upstream"

> git2r::push(repo, "upstream", "master")
Error in .local(object, ...) : 
  Error in 'git2r_push': HTTP parser error: the on_headers_complete callback failed
> git2r::push(repo, "upstream", "refs/heads/master")
Error in .local(object, ...) : 
  Error in 'git2r_push': HTTP parser error: the on_headers_complete callback failed
```

**Comment by sckott** [comment]
@cpsievert thanks. I got your eg to work with using the ssh URL instead, e.g., `git@github.com:cpsievert/git2rtest.git` instead of  `https://github.com/cpsievert/git2rtest.git` Does that work for you?

**Comment by cpsievert** [comment]
Ah, this might be part of the problem:

```r
> remote_remove(repo, "upstream")
> git2r::remote_add(repo, "upstream", "git@github.com:cpsievert/git2rtest.git")
> git2r::push(repo, "upstream", "master")
Error in .local(object, ...) : 
  Error in 'git2r_push': Unsupported URL protocol
```

It could be that I don't have SSH setup correctly (I always use https for the remote)...I'll look into it.

**Comment by sckott** [comment]
I guess that `https` to `git@` fix is somewhat beside the point, in that we'd want `https` remotes to actually work.  But I think

**Comment by cpsievert** [comment]
Yea, it appears that the `git@` remote works from my command line:

```bash
$ mkdir git2rtest
$ cd git2rtest/
/git2rtest$ echo "# git2rtest" >> README.md
/git2rtest$ git init
Initialized empty Git repository in /Users/cpsievert/Desktop/github/local/git2rtest/.git/
/git2rtest$ git add README.md
/git2rtest$ git commit -m "first commit"
[master (root-commit) 0e595ad] first commit
 1 file changed, 1 insertion(+)
 create mode 100644 README.md
/git2rtest$ git remote add origin git@github.com:cpsievert/git2rtest.git
/git2rtest$ git push -u origin master
Counting objects: 3, done.
Writing objects: 100% (3/3), 228 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To git@github.com:cpsievert/git2rtest.git
 * [new branch]      master -> master
Branch master set up to track remote branch master from origin.
```

**Comment by sckott** [comment]
hmm, don't know, opened up an issue in git2r repo, see link above

**Comment by sckott** [comment]
@cpsievert okay, changed `git2r` to a Suggest
