### ISSUE TITLE
client error: (422) Unprocessable Entity (WebDAV; RFC 4918)

### ISSUE THREAD

**Issue by cpsievert** [ropensci/gistr#41]
Sorry this isn't really a minimal example, but I'm not sure of a good way to reduce it:

```r
library(git2r)
library(gistr)
repo <- clone("https://github.com/cpsievert/AnimintTest.git", "AnimintTest")
fs <- dir("AnimintTest/FluView", full.names = TRUE)
gist_create(fs, description = "FluView")
```

```r
#> Error in list2gist(x) : Not coerceable to a gist
#> In addition: Warning message:
#>   In process(response) :
#>   client error: (422) Unprocessable Entity (WebDAV; RFC 4918)
```

**Comment by sckott** [comment]
@cpsievert you have a folder in that directory, which i think is what causes the problem.

**Comment by sckott** [comment]
@cpsievert what would you want to have happen with a folder ? e.g., recursive behavior so that all files in a folder are pushed up?  Or if a folder is found, skip it?

**Comment by cpsievert** [comment]
whoops, sorry about that, maybe you could add a check at the start of `gist_create()` like:

```r
if (any(file_test("-d", files)) stop("Can't upload directories as a gist.)
```

?

**Comment by sckott** [comment]
Yeah, that sounds good to stop if a folder is found, 

other than this issue, I think this should work even with the hundreds of files you have in your e.g.

**Comment by cpsievert** [comment]
Yea, I forgot that in `animint2dir()` we flatten the file structure (which requires changing some hrefs). I'll play around some more and report back.

**Comment by sckott** [comment]
thanks :+1:

**Comment by sckott** [comment]
added checks to `gist_create()` for binary files and directories in ad400637857160cef389267bd5245e6627b154e4

**Comment by cpsievert** [comment]
Thanks, I think it's safe to close this.

**Comment by sckott** [comment]
cool, thanks for bringing this up

**Comment by cpsievert** [comment]
No prob, I [flattened the file structure](https://github.com/cpsievert/AnimintTest/commit/e6c0735fadb82f020b5bd0c28c5ea3bb4a36e416) and now I get this error:

```r
Error: Validation Failed
resource: Gist
code: missing_field
field: files
In addition: Warning message:
In max(b) : no non-missing arguments to max; returning -Inf
```

Perhaps I've hit the limit on the _number_ of files?

Shall we migrate to another issue?

**Comment by sckott** [comment]
i'll try it again, and see if it's a diff. problem... :clock1:

**Comment by sckott** [comment]
@cpsievert that warning `In max(b) : no non-missing arguments to max; returning -Inf` was just related to a helper fxn for checking for binary files. should be fixed now in commit not yet pushed

For the large number of files you have I think using git will be much easier and faster. Have you tried that?  Is it do-able for your use case?  

Using `gist_create()` with this example, it's failing, but haven't quite tracked down exactly why yet, something with the Github API

**Comment by cpsievert** [comment]
Got it, thanks, I'll think about using **git2r** in **animint** instead (I didn't know it was on CRAN!)

**Comment by sckott** [comment]
yeah, so nice that it's on cran now
