### ISSUE TITLE
Including git fxn needs to be put off until next version of git2r is on CRAN

### ISSUE THREAD

**Issue by sckott** [ropensci/gistr#45]
@cpsievert FYI, i'm taking the git fxn out for now, putting on another branch, so that I can continue with the cran submission of the remaining changes.

**Comment by sckott** [comment]
the mentioned change https://github.com/ropensci/git2r/issues/115

**Comment by stewid** [comment]
@sckott new version of git2r is now on CRAN.

**Comment by sckott** [comment]
great :rocket:

**Comment by sckott** [comment]
wait a day or so, then I'll put git fxn back in to master branch
