### ISSUE TITLE
integrate with blockbuilder.org for post-processing

### ISSUE THREAD

**Issue by timelyportfolio** [ropensci/gistr#62]
blockbuilder.org is a very nice online gist editor primarily built for `d3.js` bl.ocks, but it could easily be used as an online gist editor for anything.  Would it be worthwhile to add a function to open a gist in blockbuilder?

**Comment by sckott** [comment]
Thanks for the issue. Do you mean that you'd create a Github gist, then open in blockbuilder? Or just create a gist in blockbuilder?

**Comment by timelyportfolio** [comment]
Sorry, I wasn't clear.  My thought was to open a gist created/updated in R in blockbuilder, so this

```
row.names(mtcars) <- NULL
gist_create_obj(mtcars)
```
could optionally open in blockbuilder.org rather than gist.github.com.

**Comment by sckott** [comment]
> open a gist created/updated in R 

by in R, do you mean created on Github gists? Or does blockbuilder have its own API to post gists?  

Do you have any code yet to do this?

**Comment by timelyportfolio** [comment]
here is some quick code, but I just realized that blockbuilder.org requires a `index.html` so it does not work in this case.  As an example of a gist created from an `htmlwidget` in `R` that works in blockbuilder, see http://blockbuilder.org/timelyportfolio/2322b6b18d8ad9d6c394.

```
library(gistr)

row.names(mtcars) <- NULL
g <- gist_create_obj(mtcars)

url <- sprintf(
  "http://blockbuilder.org/%s/%s",
  g$owner$login,
  g$id
)

browseURL(url)
```

**Comment by sckott** [comment]
We could generate an index.html right? How did you generate that `index.html`?

Also, would blockbuilder only make sense for some kinds of objects?

**Comment by timelyportfolio** [comment]
Yes, could easily generate index.html. The index.html in the provided example came from `htmlwidgets::saveWidget`.  I'm not sure it makes as much sense with objects as it does with `rmarkdown` and code.

I'm off computer for the next couple of days, but I'll be happy to experiment more.

**Comment by sckott** [comment]
Cool, when you get back would be nice to see an example with generating an index.html file that will work sending to blockbuilder

**Comment by ramnathv** [comment]
@timelyportfolio what is the use case for sending html generated from a `htmlwidget` to blockbuilder? Since `htmlwidget` inlines all supporting js/css, `index.html` would be really large and hard to edit. Thoughts?

**Comment by timelyportfolio** [comment]
Many times I want to quickly demonstrate an htmlwidget with bl.ocks.  To do this, my workflow now with blockbuilder is 

1.  experiment and refine code in R
1.  `htmlwidgets::saveWidget`
1.  edit html in RStudio to copy/paste in blockbuilder
1.  write short Readme.md
1.  copy/paste R code in Readme.md
1.  clip screen with my screenclipping and save
1.  add screenclip
1.  share with the world

Most of the time if I am only showing one `htmlwidget`, I comfortable fall < 1mb which seems to be the limit for online edit of gists.

**Comment by ramnathv** [comment]
I still fail to understand the benefit that blockbuilder provides here vs. a simple gist. `blocks.org` would render a gist with a `README.md` and `index.html`. Am I missing something here?

**Comment by sckott** [comment]
Is it worth having a fxn to open a gist in http://bl.ocks.org/ ?

**Comment by ramnathv** [comment]
@sckott Yes. I am writing some wrapper code that would use `git2r` and `gistr` to automatically save a widget to html, create a thumbnail using `webshot` and push it as a gist and open in `bl.ocks.org`. Right now, running into issues with using `gitr::push`.

**Comment by sckott** [comment]
@ramnathv we now have an interface around `git2r` (`gist_create_git()`) - though maybe you knew already

**Comment by ramnathv** [comment]
Oh. wonderful. Sorry, I have not kept up with `gistr`. I should probably do that first.

**Comment by sckott** [comment]
@ramnathv let me know if you run into any problems

**Comment by sckott** [comment]
@timelyportfolio Any thoughts on this?  Want to pursue this further?
