### ISSUE TITLE
When should getOption("github.username") be checked?

### ISSUE THREAD

**Issue by sboysel** [ropensci/gistr#67]
For example, the error for `gists(what = "mineall")` is somewhat cryptic until you realize  the `github.username` is unset

    > library(gistr)
    > gist_auth()
    <request>
    Headers:
    * Authorization: token abcdefghijklmnopqrstuvwxyz0123456789
    > gists(what = "mineall")
    Error: length(url) == 1 is not TRUE 

#66 encourages the user to manually set the option if `gists(what = "mineall")` is run when unset.

**Comment by sckott** [comment]
Thanks - looks like that's the only function that looks for the R option `github.username` so your PR sorts that out. After merging I'll add a note to the docs that users should make sure they have those options set.
