### ISSUE TITLE
File argument

### ISSUE THREAD

**Issue by maelle** [ropensci/gistr#72]
Cool package!

* `gist_create` doesn't check whether there is a file or a code before sending something to the API. You can write `gistr::gist_create()` with no arguments which I think one shouldn't be allowed to?

* I wonder whether it'd be possible to post the active document by default? Or maybe that's an RStudio concept? It'd be cool to work on an R script, then post it without having to enter its location.

**Comment by sckott** [comment]
Good idea that it shouldn't be able to take no arguments. Should be given either `file` or `code` argument, so can fail if neither of those given

**Comment by maelle** [comment]
not necessarily, just one where I'm too lazy to type the path and want the function to understand I mean "this one"

**Comment by sckott** [comment]
okay, the first issue is fixed, have to pass in files or code now

**Comment by maelle** [comment]
cool, thx!

**Comment by sckott** [comment]
@maelle i totally forgot until now about https://github.com/MilesMcBain/gistfo - @MilesMcBain has already got it covered

**Comment by maelle** [comment]
Right 😀 (I saw it again because of #73 , shoult gistfo be mentioned iin gistr docs?) 

so it doesn't make sense for `gistr` itself to recognise the active document?

**Comment by sckott** [comment]
Yes, we should mention gistfo here. 

> so it doesn't make sense for `gistr` itself to recognise the active document?

I don't think so, since `gistfo` already does it, and since it imports this pkg, it'd be a bit weird to then do what `gistfo` does here i think

**Comment by maelle** [comment]
Makes sense!
