### ISSUE TITLE
feature request: host arg to gist_create() family 

### ISSUE THREAD

**Issue by ijlyttle** [ropensci/gistr#75]
Would it be possible to add a `host` argument to the `gist_create` family of functions? This would allow people to create gists on their instance of GitHub Enterprise.

I would be happy to make a PR (or a series of PRs). 

I may be getting ahead of myself, but I could start with `gist_create_git()`. 

Other than the `gist_create()` family, I imagine that `gist_auth()` would be affected. Others?

Thanks!

**Comment by sckott** [comment]
Thanks for this issue @ijlyttle 

short answer: probably 🤔 

Would it just be changing the base url? its defined here https://github.com/ropensci/gistr/blob/master/R/zzz.R#L65

one issue i see is that i wouldn't be able to test it. e.g. i imagine there's a suite of other login options for GH enterprise (single sign on, etc.)?

**Comment by ijlyttle** [comment]
I will gladly take a probably, thanks 😀

If I were to start with `git_create_git()`, it may be a bit simpler - at least initially...

In this case, I (think I) could work with these lines: https://github.com/ropensci/gistr/blob/8f74ca7abd91471f5e7355b1425ed8ae45e12e02/R/gist_create_git.R#L182-L186

For the other cases, I can see it will be a bit more challenging 😓

I agree that testing becomes an issue - I did something like this for devtools (now usethis): https://github.com/r-lib/devtools/issues/1101. The conclusion was that as along as the tests remained passing for "public" github, I could vouch for it working privately. 

My experience on the usethis PR is that the authentication works substantially the same, using SSH keys or PAT. There, we added a `host` argument and a `auth_token` argument. Both default to`NULL`; you can provide your own values for using GH enterprise - this might be my first idea here: 

https://github.com/r-lib/usethis/blob/89d5a39cd220a3f319f8b7ea471268053bf1cfbe/R/github.R#L57-#L62

I propose to make a first PR for `git_create_git()` to see how it turns out. If you end up thinking it is unworkable, that will be my risk to take 😀

Thanks!

**Comment by sckott** [comment]
That seems reasonable that if it passes with public github then it should be okay with private. 

A PR for `gist_create_git` sounds good.

**Comment by sckott** [comment]
@ijlyttle do you think you'll revisit this as you said in the PR? or should I close?

**Comment by ijlyttle** [comment]
Let's close - sorry for letting this hang for so long...

**Comment by sckott** [comment]
no worries, thx
