### ISSUE TITLE
Error: Problems parsing JSON

### ISSUE THREAD

**Issue by maelle** [ropensci/gistr#77]
``` r
reprex::reprex(plot(1:10),
               outfile = "myreprex")
#> Preparing reprex as .R file:
#>   * myreprex_reprex.R
#> Rendering reprex...
#> Writing reprex markdown:
#>   * myreprex_reprex.md
#> Rendered reprex is on the clipboard.

suppfiles <- fs::dir_ls("myreprex_reprex_files", 
                        recursive = TRUE)
suppfiles <- suppfiles[fs::is_file(suppfiles)]
files <- c("myreprex_reprex.md", 
           suppfiles,
           "myreprex_reprex.R")
gistr::gist_create(files = files,
                   description = "my reprex")
#> Error: Problems parsing JSON
```

<sup>Created on 2018-09-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by maelle** [comment]
@cderv this was my experimenting with the same idea as yours :wink: https://github.com/tidyverse/reprex/issues/190

**Comment by sckott** [comment]
forgot we've dealt with this before , see 

- https://github.com/ropensci/gistr/issues/33
- https://github.com/ropensci/gistr/issues/4

cant upload binary files with the http api, so got to use git flow instead

see if this example works https://github.com/ropensci/gistr/blob/master/R/gist_create_git.R#L79-L85

**Comment by maelle** [comment]
Thanks. Now I get a `git2r` error for a change, with the CRAN version, so I'll need to install a dev version probably.

``` r


reprex::reprex(plot(1:10),
               outfile = "myreprex")
#> Preparing reprex as .R file:
#>   * myreprex_reprex.R
#> Rendering reprex...
#> Writing reprex markdown:
#>   * myreprex_reprex.md
#> Rendered reprex is on the clipboard.

suppfiles <- fs::dir_ls("myreprex_reprex_files", 
                        recursive = TRUE)
suppfiles <- suppfiles[fs::is_file(suppfiles)]
fs::file_move(suppfiles, getwd())
files <- c("myreprex_reprex.md", 
           fs::path_file(suppfiles),
           "myreprex_reprex.R")
gistr::gist_create_git(files = files,
                   description = "my reprex")
#> Error in sprintf("%s/?|\\./", git@path): trying to get slot "path" from an object (class "git_repository") that is not an S4 object
```

<sup>Created on 2018-09-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by sckott** [comment]
FWIW i have the CRAN version of `git2r`

**Comment by maelle** [comment]
But you don't use Windows :wink: I'm installing the dev version, I might report the bug over there if I still get the error.

**Comment by sckott** [comment]
ok, thanks

**Comment by maelle** [comment]
My problems are now linked to `git2r`/ssh/Windows as usual, not to `gistr`, so closing this. Thank you!
