### ISSUE TITLE
Example use case with round trip data.frame

### ISSUE THREAD

**Issue by jsta** [ropensci/gistr#78]
The current use case example of writing json text is great. Maybe a `data.frame` example might also be useful? I suspect there is a cleaner way of doing this but I worked out one way of round tripping a `data.frame` to gist: https://gist.github.com/jsta/b8e18d281f70f755bede10af8997b63e

**Comment by sckott** [comment]
thanks @jsta example where? readme? somewhere else?

that example looks good to me

**Comment by jsta** [comment]
Maybe in `inst/vign/gistr_vignette.Rmd`? Seems like the vignette is manually synced with the README.

**Comment by sckott** [comment]
That vignette is a good place  - PR if you have time to that location. I am a weird one, i like to have vignettes pre-rendered so users don't have to build vignettes and they aren't built on check 😛
