### ISSUE TITLE
GITHUB_PAT error on travis

### ISSUE THREAD

**Issue by tdhock** [ropensci/gistr#80]
Hi, I trying to post a gist in a test on travis, and this has worked fine in the past, but recently I am getting a "please set GITHUB_PAT" error on travis https://travis-ci.org/tdhock/animint2/jobs/583994090#L8681 but I have set GITHUB_PAT in my Travis Repository settings, as described in the travis docs here https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings

Did something change recently which could cause this?

Any other ideas to fix?

Thanks in advance.

**Comment by sckott** [comment]
I don't know of anything that changed. What version of gistr and R?

**Comment by tdhock** [comment]
travis says R-3.6.1 https://travis-ci.org/tdhock/animint2/jobs/583994090#L672 and gistr-0.4.2 https://travis-ci.org/tdhock/animint2/jobs/583994090#L925

**Comment by sckott** [comment]
thanks, looking

**Comment by sckott** [comment]
i just looked at gistr travis builds and they're also faililng, seems that the PAT needs to have `gist` scope selected. I can't remember if that was available years back or not, but anyway, the PAT you use has to have gist scope. updating the docs now.

**Comment by tdhock** [comment]
my PAT does have gist scope.

**Comment by sckott** [comment]
hmm, in the raw travis log it has

```
Setting environment variables from .travis.yml
$ export R_REMOTES_NO_ERRORS_FROM_WARNINGS=TRUE
$ export TEST_SUITE=compiler
```

this repo on travis raw log has 

```
Setting environment variables from repository settings
$ export CODECOV_TOKEN=[secure]
$ export GITHUB_PAT=[secure]
```

i'd think the travis log would show that a GITHUB_PAT env var was set if it was provided, or no?

**Comment by tdhock** [comment]
I'd think so as well. I see in my travis settings that there is GITHUB_PAT defined, but I don't see "Setting environment variables from repository settings" in my travis build log. Is there some other option I need to enable / use in order to get it to work?

**Comment by sckott** [comment]
ah, [that link](https://travis-ci.org/tdhock/animint2/jobs/583994090#L8681) is to a a PR  - repository env vars aren't avail to PR's AFAIK

**Comment by tdhock** [comment]
ok thanks
