### ISSUE TITLE
New Maintainer Wanted :-)

### ISSUE THREAD

**Issue by maelle** [ropensci/gistr#85]
Or a new maintainer _team_ :smile_cat: 

If you're interested, please comment in the issue. 

For more info, see

* [our guidance on _Changing package maintainers_](https://devguide.ropensci.org/changing-maintainers.html);
* [our _Package Curation Policy_](https://devguide.ropensci.org/curationpolicy.html).

**Comment by Athene-ai** [comment]
I am interested

**Comment by maelle** [comment]
The gist API is an example in https://httr2.r-lib.org/articles/wrapping-apis.html#github-gists-api

**Comment by maelle** [comment]
I'm wondering whether I should archive this package @sckott @jthomasmock (or put the call in next week's newsletter once again as it's a fairly general API).

**Comment by sckott** [comment]
Doesn't matter to me, if you think archiving is the best move, please do.

**Comment by jmuhlenkamp** [comment]
I may be interested in maintaining this package.  Will need a few (hopefully short) weeks to look under the hood and come to a decision.  I'm comfortable with developing R packages, but not familiar with the details of `gistr`.  Would also be open to teaming up with any others who may be interested.  Will try to follow-up again by early July.

**Comment by maelle** [comment]
Ok, let's keep this open, thanks a lot for commenting!

**Comment by ScientificProgrammer** [comment]
Hi:

I'm interested in helping out as a maintainer. Although I'm not familiar with the `gistr` package, I have many years of experience coding in `C`, `C++`, `Python`, and, of course, `R`. Please let me know how I can help.

**Comment by maelle** [comment]
Thanks a lot @ScientificProgrammer!

Once @jmuhlenkamp comments again, I can give you both access to the repository.

**Comment by ScientificProgrammer** [comment]
> Once @jmuhlenkamp comments again, I can give you both access to the repository.

OK, that sounds good. Once we have access, can you give me some guidance on where I can help most?

At present, I see only one open issue, #84. I read through the thread, and I'm not sure if I understand what's being asked. For example, based on your [last reply](https://github.com/ropensci/gistr/issues/84#issuecomment-1140975704) to the individual who opened the issue, do you think he should simply use the [httr2](https://github.com/r-lib/httr2/) package to roll his own solution, or, since the issue is open, do you think we should implement a solution for the code base?

I look forward to helping!

**Comment by maelle** [comment]
Well depending on who ends up being on board, y'all will need to decide whether to keep using crul or to convert the code to using httr2, and also to decide what is in scope.
Thank you!

**Comment by ScientificProgrammer** [comment]
> "_Well depending on who ends up being on board, y'all will need to decide..._

Thank you for the helpful reply. Just for my clarity, are the existing maintainers leaving the project altogether? Even if that's the case, would they still be available for the new maintainers to ask the occasional question? I'm fine either way, but having the benefit of their knowledge would be very helpful.

**Comment by sckott** [comment]
I'm available to answer questions, but i won't have time to write any code, etc

**Comment by ScientificProgrammer** [comment]
> I'm available to answer questions, but i won't have time to write any code, etc

Knowing that you'll be avaliable to give occasional input and guidance makes me feel much more confident about taking on a maintainer role. Thank you for all of the great work you've done and for being willing to help out with questions and advice!

**Comment by jmuhlenkamp** [comment]
Hi all, great to see some chatter in here!  After careful consideration I'm not confident I will have the availability in the near-term to be a proper maintainer.  @ScientificProgrammer all yours, thanks in advance!

**Comment by XenicLabs** [comment]
Hi @jmuhlenkamp 

> "_I'm not confident I will have the availability in the near-term to be a proper maintainer._"

I do understand and respect your decision. However, I encourage you to think about joining me. Just having another person available even to discuss the occasional idea is so helpful.

**Comment by ScientificProgrammer** [comment]
Hi @jmuhlenkamp 

> "_I'm not confident I will have the availability in the near-term to be a proper maintainer._"

I do understand and respect your decision. However, I encourage you to think about joining me. Just having another person available even to discuss the occasional idea is so helpful.

---

`PS: My apologies for the previously deleted comment. It was from a work related account.`

**Comment by maelle** [comment]
Thanks @jmuhlenkamp!

@ScientificProgrammer I've added you to a team that has admin access to this repository. Note that you'll need to have enabled two-factor authentication for your GitHub account https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication (see also https://ropensci.org/blog/2022/05/16/requiring-2fa-for-the-ropensci-github-organization/ and https://ropensci.org/blog/2022/03/22/safeguards-and-backups-for-github-organizations/ for context).

**Comment by maelle** [comment]
@ScientificProgrammer what is your email address? Asking so that rOpenSci community manager @yabellini might send you an invitation to rOpenSci slack workspace. 

Also feel free to ask me any question by pinging me in GitHub issues, or using our forum https://discuss.ropensci.org/
