### ISSUE TITLE
Auth authentication error

### ISSUE THREAD

**Issue by PatentInsights** [ropensci/gistr#86]
I have an issue very similar to  OAuth authenitication error #83.  I have created a Personal Access Token in GIT, ticking the box for writing gists,  and saved this using the line of text - Sys.setenv(GITHUB_PAT = "ghpblahblah") - where "ghpblahblah" was the token generated, which starts with "ghp".  I can see in RStudio (Sys.getenv()) that the token is "ghpblahblahblah", as it should be.

However I run the command get("auth_config", envir=gistr:::cache)$auth_token$credentials$access_token, I end up with another token, beginning with "gho" this time, and the error message.

I note that when I run the command gist_auth(), I do not get a new browser tab opening asking me to verify my authentication. 

More to the point, when I try to write a new gist

gist_create(public=FALSE, browse=FALSE, filename="test.txt", code="test")

I end up with the following error message:

GitHub response headers suggest no or insufficient scopes
To create gists you need the `gist` OAuth scope on your token.

What I am doing wrong?

<details> <summary><strong>Session Info</strong></summary>

```r
gist_create(public=FALSE, browse=FALSE, filename="test.txt", code="test")
```

</details>

**Comment by ScientificProgrammer** [comment]
Hi @PatentInsights:

Currently, I am [weighing implementing](https://github.com/ropensci/gistr/issues/84#issuecomment-1133027245) the `httr2` package which should make `oauth` authentication simpler and more robust than it is currently. I have just assumed responsibility for maintaining the [gistr](https://github.com/ropensci/gistr) package, so I'm still trying to figure out where best to start. I will follow up ASAP.

**Comment by PatentInsights** [comment]
Thanks! I got there in the end....but it was more difficult than it could
have been. But this may have been partially due to incomplete documentation.

Warm regards,



*Mike Lloyd                              *
*Director*
Patent-Insights Pty Ltd <https://www.patent-insights.com/>:

Commercially-focused IP searching and analytics
Australasian agent for* Patseer <https://patseer.com/>* patent search and
analytics software

Melbourne, Australia
+61 419 103 533

**Comment by ScientificProgrammer** [comment]
Hi Mike,

Thanks for closing the loop on this issue. I'll go ahead and close the issue. However, before I do, if you want to share any insights with me, such as suggestions for how best to update the documentation for the current implementation, I'm very interested in your input.

I'm still studying the package's current implementation, which also includes trying to decide how much emphasis I should place on coding enhancements versus updating the documentation. Your specific issue appears to be a great candidate for the latter.

Perhaps, like most software developers, I prefer writing code much more than writing documentation. However, I'm forcing myself to be more disciplined in striking this balance.

**Comment by PatentInsights** [comment]
Hello Eric,

Thank you for your enthusiasm.

I looked up my old project files. I am relatively new at this, and the
answer turned out to be the suffix: gist_auth(reauth = T).

So:

Sys.setenv(GITHUB_PAT = "PAT with gist scopes enabled here")
gist_auth(reauth = T).

I had previously set up another gist scope, and this was interfering with
the setting of the scope.

**Comment by ScientificProgrammer** [comment]
That's very helpful. I've made a similar mistake countless times, and from a software side, it's fairly easy to check permissions, then give more descriptive feedback when something fails. For now, I'll put a note in the documentation, but I'll also look into the current code to see how it works. If I'm unable to easily perform a more automated diagnostic for permissions, perhaps by returning a more descriptive error message, such as a suggestion that the user check their PAT permissions and confirm that it has the appropriate gist permissions, it'll save future users some time. Thanks again for your help!
