### ISSUE TITLE
Need help with 2 CI/CD action failures after making 2 relatively minor updates and then pushing to the master branch

### ISSUE THREAD

**Issue by ScientificProgrammer** [ropensci/gistr#89]
Hi @maelle and @sckott,

Recently, I made two updates to the repo, which I thought would be very minor. These changes, which were in relation to Issue #87  and #88. Because I didn't anticipate any serious issues due to these updates being so minor, I just edited them directly via the Github website editor and pushed the changes to the `master` branch.

Unfortunately, I just noticed that the CI/CD checks for these updates failed. However, I cannot make any sense of the reason for the failures.

- [ ] Resolve failed CI/CD Workflow Action Checks
   - [ ] [R-checks Action &#35;9](https://github.com/ropensci/gistr/actions/runs/3223470042)
   - [ ] [R-checks Action &#35;10](https://github.com/ropensci/gistr/actions/runs/3223495567)

## R-checks Action Num 9 Summary
![image](https://user-images.githubusercontent.com/4348294/196274458-a99a4ab7-551e-4f28-a82b-32ff9fdd8520.png)

## R-checks Action Num 10 Summary
![image](https://user-images.githubusercontent.com/4348294/196274568-d5dfd27d-e712-4176-8848-988ffc798260.png)

---

Can either of you help me resolve these failures?

Thanks!

**Comment by sckott** [comment]
I see that some tests in `test-star.R`  are failing. I'd first see if I can replicate the problem locally. Can you?

**Comment by maelle** [comment]
I think at least part of the problem comes from the GitHub Actions workflow being so old, I modernized it by using `usethis::use_github_action_check_standard()` cf https://usethis.r-lib.org/reference/github_actions.html (in #91)
